<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/* 
 * Pagination Config Bootstrap 3 CSS Style
 * harviacode.com
 */

$config['query_string_segment'] = 'start';

$config['full_tag_open'] = '<div class="card-tools">
                    <ul class="pagination pagination-sm">';
$config['full_tag_close'] = '</ul>
                </div>';

$config['first_link'] = 'First';
$config['first_tag_open'] = '<li><button type="button" class="btn btn-block btn-outline-success btn-flat btn-sm">';
$config['first_tag_close'] = '</button></li>';

$config['last_link'] = 'Last';
$config['last_tag_open'] = '<li><button type="button" class="btn btn-block btn-outline-success btn-flat btn-sm">';
$config['last_tag_close'] = '</button></li>';

$config['next_link'] = '>>';
$config['next_tag_open'] = '<li><button type="button" class="btn btn-block btn-outline-success btn-flat btn-sm">';
$config['next_tag_close'] = '</button></li>';

$config['prev_link'] = '<<';
$config['prev_tag_open'] = '<li><button type="button" class="btn btn-block btn-outline-success btn-flat btn-sm">';
$config['prev_tag_close'] = '</button></li>';

$config['cur_tag_open'] = '<li class="active"><button type="button" class="btn btn-success btn-flat btn-sm">';
$config['cur_tag_close'] = '</button></li>';

$config['num_tag_open'] = '<li class="page-item"><button type="button" class="btn btn-block btn-outline-success btn-flat btn-sm">';
$config['num_tag_close'] = '</button></li>';



/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-14 23:15:06 */
/* http://harviacode.com */