<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Guru_model extends CI_Model
{

    public $table = '88_guru';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
        function json() {
        $this->datatables->select('id,id_guru,name,ttl,pendidikan_terakhir,tgl_mulai_kerja,jabatan,role_id,image,id_kelas,password');
        $this->datatables->from('88_guru');
        //add this line for join
        //$this->datatables->join('table2', '88_guru.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('guru/read/$1'),'<button type="button" class="btn btn-outline-primary btn-xs btn-flat"><i class="fas fa-search-plus"></i></button>')." 
         ".anchor(site_url('guru/update/$1'),'<button type="button" class="btn btn-outline-primary btn-xs btn-flat"><i class="fas fa-edit"></i></button>')." 
         ".anchor(site_url('guru/delete/$1'),'<button type="button" class="btn btn-outline-primary btn-xs btn-flat"><i class="fas fa-trash"></i></button>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_guru', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('ttl', $q);
	$this->db->or_like('pendidikan_terakhir', $q);
	$this->db->or_like('tgl_mulai_kerja', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('role_id', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('password', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_guru', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('ttl', $q);
	$this->db->or_like('pendidikan_terakhir', $q);
	$this->db->or_like('tgl_mulai_kerja', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('role_id', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('password', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Guru_model.php */
/* Location: ./application/models/Guru_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-08 01:18:33 */
/* http://harviacode.com */