<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategori_mutabaah_model extends CI_Model
{

    public $table = '99_kategori_mutabaah';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
        function json() {
        $this->datatables->select('id,id_kategori,nama_kategori');
        $this->datatables->from('99_kategori_mutabaah');
        //add this line for join
        //$this->datatables->join('table2', '99_kategori_mutabaah.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('kategori_mutabaah/read/$1'),'<button type="button" class="btn btn-outline-primary btn-xs btn-flat"><i class="fas fa-search-plus"></i></button>')." 
         ".anchor(site_url('kategori_mutabaah/update/$1'),'<button type="button" class="btn btn-outline-primary btn-xs btn-flat"><i class="fas fa-edit"></i></button>')." 
         ".anchor(site_url('kategori_mutabaah/delete/$1'),'<button type="button" class="btn btn-outline-primary btn-xs btn-flat"><i class="fas fa-trash"></i></button>','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_kategori', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_kategori', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kategori_mutabaah_model.php */
/* Location: ./application/models/Kategori_mutabaah_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-04 16:15:26 */
/* http://harviacode.com */